// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UserCenter.Core.Models;

public partial class User
{
    public long Id { get; set; }

    public string Username { get; set; }

    public string UserAccount { get; set; }

    public string AvatarUrl { get; set; }

    public short? Gender { get; set; }

    public string UserPassword { get; set; }

    public string Phone { get; set; }

    public string Email { get; set; }

    public int? UserStatus { get; set; }

    public DateTime? CreateTime { get; set; }

    public DateTime? UpdateTime { get; set; }

    public short? IsDelete { get; set; }

    public int? UserRole { get; set; }
}